import type { Activity } from '../types/activity';

export const MOCK_ACTIVITIES: Record<string, () => Activity> = {
  spotify: () => ({
    id: 'activity-spotify',
    app: 'Spotify',
    type: 'media',
    title: 'Blinding Lights',
    subtitle: 'The Weeknd — After Hours',
    icon: 'Music',
    progress: 0.42,
    timeRemaining: '1:54',
    duration: 200,
    priority: 80,
    actions: [
      { id: 'prev', label: 'Previous', icon: 'SkipBack' },
      { id: 'play', label: 'Pause', icon: 'Pause', variant: 'primary' },
      { id: 'next', label: 'Next', icon: 'SkipForward' },
    ],
    createdAt: Date.now(),
  }),

  pomodoro: () => ({
    id: 'activity-pomodoro',
    app: 'Focus Timer',
    type: 'timer',
    title: 'Deep Work Session',
    subtitle: 'Pomodoro #3 of 4',
    icon: 'Timer',
    progress: 0.68,
    timeRemaining: '08:12',
    duration: 1500,
    priority: 75,
    actions: [
      { id: 'pause', label: 'Pause', icon: 'Pause' },
      { id: 'stop', label: 'Finish', icon: 'Square', variant: 'danger' },
    ],
    createdAt: Date.now(),
  }),

  download: () => ({
    id: 'activity-download',
    app: 'Steam',
    type: 'download',
    title: 'Cyberpunk 2077: Phantom Liberty',
    subtitle: '45.2 MB/s — 18.4 GB / 24.0 GB',
    icon: 'Download',
    progress: 0.76,
    timeRemaining: '2m 14s',
    priority: 60,
    actions: [
      { id: 'pause', label: 'Pause', icon: 'Pause' },
      { id: 'cancel', label: 'Cancel', icon: 'X', variant: 'danger' },
    ],
    createdAt: Date.now(),
  }),

  grabFood: () => ({
    id: 'activity-grab',
    app: 'GrabFood',
    type: 'custom',
    title: 'Tài xế đang giao đơn hàng',
    subtitle: 'Trà Sữa Phúc Long • 6 phút nữa đến',
    icon: 'Bike',
    progress: 0.85,
    timeRemaining: '6 mins',
    priority: 90,
    actions: [
      { id: 'call', label: 'Gọi tài xế', icon: 'Phone', variant: 'primary' },
    ],
    createdAt: Date.now(),
  }),

  flight: () => ({
    id: 'activity-flight',
    app: 'Flighty',
    type: 'navigation',
    title: 'VN230: SGN ➔ HAN',
    subtitle: 'Đang bay qua Đà Nẵng (FL360) • Đến lúc 14:15',
    icon: 'Plane',
    progress: 0.55,
    timeRemaining: '45 mins',
    priority: 70,
    createdAt: Date.now(),
  }),

  sports: () => ({
    id: 'activity-sports',
    app: 'Premier League',
    type: 'custom',
    title: 'Arsenal 2 - 1 Chelsea',
    subtitle: 'Saka 34\', Odegaard 62\' • Phút 78\'',
    icon: 'Trophy',
    progress: 0.86,
    timeRemaining: '78\'',
    priority: 65,
    createdAt: Date.now(),
  }),

  github: () => ({
    id: 'activity-github',
    app: 'GitHub Actions',
    type: 'custom',
    title: 'Build & Deploy Production',
    subtitle: 'Run #482 • main branch (passing tests)',
    icon: 'GitBranch',
    progress: 0.9,
    timeRemaining: '30s',
    priority: 55,
    createdAt: Date.now(),
  }),

  system: () => ({
    id: 'activity-system',
    app: 'System Monitor',
    type: 'system',
    title: 'CPU 24% • RAM 58%',
    subtitle: 'Network: ↓ 12.4 MB/s ↑ 2.1 MB/s',
    icon: 'Activity',
    progress: 0.58,
    priority: 40,
    createdAt: Date.now(),
  }),
};
